### ISSUE TITLE
PostgreSQL 13 and GDB

### ISSUE THREAD

**Issue by ArturFormella** [StarfishStorage/explain-running-query#1]
Hello! I have the following error and I can't find any solution.

```
sudo python3 ./explain-running-query.py 3153577
INFO: Waiting for low-level functions to finish. This may take a while.
WARNING: Terminating gdb process (PID: 3172129)
Traceback (most recent call last):
  File "./explain-running-query.py", line 253, in <module>
    sys.exit(main())
  File "./explain-running-query.py", line 245, in main
    stdout, stderr = gdb.communicate("quit", timeout=3)
  File "/usr/lib/python3.8/subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1867, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1068, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['gdb', '--silent', '--pid', '3153574']' timed out after 3 seconds
```
So I've changed timeout on line 245 to 30s. 
```
sudo python3 ./explain-running-query.py 3153577
INFO: Waiting for low-level functions to finish. This may take a while.
[Inferior 1 (process 3153577) exited normally]
The program being debugged exited while in a function called from GDB.
Evaluation of the expression containing the function
(ExplainPrintPlan) will be abandoned.
You can't do that without a process to debug.
Cannot access memory at address 0x55fa5b410788
```

What I have installed:
```
sudo apt-get install gdb
sudo apt-get install postgresql-12-dbgsym
sudo service postgresql restart
```

My query is a CTE with an UPDATE section, but simple count(1) works good:
```
sudo python3 ./explain-running-query.py 3159557
INFO: Waiting for low-level functions to finish. This may take a while.
Query Text: SELECT count(*) FROM generate_series(1, 200000000)
Plan:
Aggregate  (cost=2500000.00..2500000.01 rows=1 width=8)
  ->  Function Scan on generate_series  (cost=0.00..2000000.00 rows=200000000 width=0)
Detaching from program: /usr/lib/postgresql/13/bin/postgres, process 3159557
[Inferior 1 (process 3159557) detached]
```

Do you have any suggestions?
Thanks for your attention.

**Comment by marcinbarczynski** [comment]
Thanks for reporting the issue. 
That's odd. In general, CTEs with UPDATE section work fine. Could you please share your query?
